nested-model-form-196/config/routes.rb
Rails.application.routes.draw do
  get '/', to: redirect('/surveys')
  resources :surveys
end

nested-model-form-196/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

nested-model-form-196/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true
end

nested-model-form-196/app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true
end

nested-model-form-196/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, { questions_attributes: [:id,
                                                                     :content,
                                                                     :_destroy,
                                                                     { answers_attributes: [:id, :content, :_destroy] }] })
    end
end

nested-model-form-196/app/helpers/answers_helper.rb
module AnswersHelper
end

nested-model-form-196/app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, form, association)
    new_object = form.object.send(association).klass.new
    id = new_object.object_id
    fields = form.fields_for(association, new_object, child_index: id) do |builder|
      # render partial
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: 'add_fields', data: { id: id, fields: fields.gsub("\n", "") })
  end
end

nested-model-form-196/app/helpers/questions_helper.rb
module QuestionsHelper
end

nested-model-form-196/app/helpers/surveys_helper.rb
module SurveysHelper
end

nested-model-form-196/app/views/answers/_answer.html.erb
<li><%= answer.content %></li>

nested-model-form-196/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedModelForm196</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

nested-model-form-196/app/views/questions/_question.html.erb
<ol class="questions">
  <li>
    <%= question.content %>
    <ol class="answers"><%= render question.answers %></ol>
  </li>
</ol>

nested-model-form-196/app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, 'Answer' %>
  <%= f.text_field :content %>
  <%= f.hidden_field :_destroy %>
  <%= link_to 'Remove', '#', class: 'remove_fields' %>
</fieldset>

nested-model-form-196/app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Question", f, :questions %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nested-model-form-196/app/views/surveys/_question_fields.html.erb
<fieldset>
  <%= f.label :content, 'Question' %><br>
  <%= f.text_area :content %><br>
  <%= f.hidden_field :_destroy %>
  <%= link_to 'Remove', '#', class: 'remove_fields' %>
  <%= f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields 'Add Answer', f, :answers %>
</fieldset>

nested-model-form-196/app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

nested-model-form-196/app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

nested-model-form-196/app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

nested-model-form-196/app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>
<%= render @survey.questions %>
<%= link_to 'Edit', edit_survey_path %>&nbsp;|&nbsp;<%= link_to 'Back to surveys', surveys_path %>